#!/usr/bin/env python

import os
from kliko.validate import validate
from main import so_something_on_folder

parameters = validate()

print("the parameters: " + str(parameters))

print("content of /input: " + str(os.listdir('/input')))


so_something_on_folder('/input', '/output')


